services:
  db:
    image: postgres
    container_name: tppe_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tppe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

  backend:
    build: ./backend
    container_name: tppe_backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tppe
    networks:
      - minha-rede
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npx prisma migrate deploy && npm run test || true && npm run dev"

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: tppe_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - minha-rede
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  minha-rede:
    driver: bridge
