version: '3.8'

services:
  db:
    image: postgres
    container_name: tppe_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tppe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha-rede

  backend:
    build: ./backend
    container_name: tppe_backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tppe
    networks:
      - minha-rede
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run test && npm run dev"

volumes:
  pgdata:

networks:
  minha-rede:
    driver: bridge
