name: CI Completa (Frontend, Backend e Banco de Dados)

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend 
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^18.16.18' 
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json' 

    - name: Instalar Dependências do Frontend
      run: npm install

    # - name: Rodar Testes do Frontend
      # run: npm test 

    - name: Construir o Frontend (Verificação de Build)
      run: npm run build 

  backend_ci:
    runs-on: ubuntu-latest
    # Remova o 'defaults.run.working-directory' daqui para ter controle granular
    # defaults:
    #   run:
    #     working-directory: ./backend

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Listar arquivos na raiz do repositório (Para Depuração - Opcional, pode remover depois)
      run: ls -la ${{ github.workspace }}
      working-directory: ${{ github.workspace }} 

    - name: Configurar Node.js para Backend
      uses: actions/setup-node@v4
      with:
        node-version: '^18.16.18' 
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    
    - name: Limpar Cache NPM (Tentativa de correção EACCES)
      run: npm cache clean --force
      working-directory: ./backend

    - name: Subir o Banco de Dados e Backend com Docker Compose
      run: |
        docker compose -f docker-compose.yml up -d db backend
        echo "Aguardando o banco de dados iniciar..."
        sleep 15 
        docker compose ps
      working-directory: ${{ github.workspace }} 
      env:
        DB_HOST: db 
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: tppe

    - name: Instalar Dependências do Backend
      run: npm install
      working-directory: ./backend
      env:
        npm_config_optional: false

    - name: Rodar Migrações do Banco de Dados
      run: npx prisma migrate deploy
      working-directory: ./backend 

    - name: Rodar Testes do Backend
      run: npm test
      working-directory: ./backend 

    - name: Derrubar Serviços Docker Compose
      if: always() 
      run: docker compose -f docker-compose.yml down -v
      working-directory: ${{ github.workspace }} 
